// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2BJ-PA7-kexcTWOK-D1J259R2gMn5m8',
    appId: '1:332970839647:web:0eadaf90d62ffa9c5615ea',
    messagingSenderId: '332970839647',
    projectId: 'flutterdicoding-26f34',
    authDomain: 'flutterdicoding-26f34.firebaseapp.com',
    storageBucket: 'flutterdicoding-26f34.appspot.com',
    measurementId: 'G-6KNF3DTVZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4LQra46na88PXru70FKfymvJ0oAcpcDM',
    appId: '1:332970839647:android:b48d63cdc4cd7dfb5615ea',
    messagingSenderId: '332970839647',
    projectId: 'flutterdicoding-26f34',
    storageBucket: 'flutterdicoding-26f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArh3v36Kq5CnUJmdAYCY5sxJBn0ivpemY',
    appId: '1:332970839647:ios:956984ab789cc2785615ea',
    messagingSenderId: '332970839647',
    projectId: 'flutterdicoding-26f34',
    storageBucket: 'flutterdicoding-26f34.appspot.com',
    iosClientId: '332970839647-fvnp2qv6mjk7l0q8970i10crgm2dtt2k.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
